disabled_rules:
  - trailing_whitespace
  - identifier_name
  - cyclomatic_complexity
  - comment_spacing

opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - fallthrough
  - first_where
  - literal_expression_end_indentation
  - modifier_order
  - multiline_function_chains
  - multiline_parameters
  - operator_usage_whitespace
  - private_action
  - private_outlet
  - switch_case_on_newline
  - unavailable_function

excluded:
  - Pods
  - build*/

# Custom Rules
line_length: 200
file_length: 550
function_body_length: 100
type_body_length: 300
